version: "3"

services:
  drupal:
    image: https://hub.docker.com/repository/docker/renaudperrai/ctf/general
    deploy:
      replicas: 5
  bdd:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD: drupalPass
    volumes:
      - bdd:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ./bdd/pgdata:/var/lib/postgresql

volumes:
  bdd:
    driver: local
