version: "3"

services:
  drupal:
    image: renaudperrai/ctf:stage5
    deploy:
      replicas: 5
    ports:
      - 80:80
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=drupalPass
    volumes:
      - ./bdd/pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

volumes:
  bdd:
