version: "3"

services:
  drupal:
    image: renaudperrai/ctf:stage4
    deploy:
      replicas: 5
    ports:
      - 3000:3000
  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
